# .air.toml
root = "."

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  include_ext = [".go"]
  exclude_dir = ["tmp", "docs", "vendor", "database/postgres-data", "database/postgres-test-data"]
  exclude_file = []
  delay = 1000
  log = "stdout"
  send_interrupt = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[log]
  time = true
